version: "3.2"

services:
  # Catalog
  frontend-catalog:
    image: 'chaphe/frontend-catalog-image:1.0'
    ports:
      - "81:80"
    networks:
      - book-store-network

  # Reviews
  frontend-reviews:
    image: 'chaphe/frontend-reviews-image:1.0'
    environment:
      - REVIEWS_URL=http://localhost:3000
    ports:
      - "82:80"
    networks:
      - book-store-network

  # Store

  frontend-store:
    image: 'chaphe/frontend-store-image:1.0'
    environment:
      - STORE_URL=http://localhost:8082
      - REVIEWS_URL=http://localhost:3000
      - CATALOG_URL=http://localhost:8081
    ports:
      - "80:80"
    networks:
      - book-store-network

      
networks:
  book-store-network:
    driver: bridge