version: "3.2"

services:

  backend-reviews:
    image: 'chaphe/backend-reviews-image:1.0'
    environment:
      - MONGODB_HOST=mongodb-reviews
    ports:
      - "3000:3000"
    networks:
      - book-store-network

  # CATALOG
  backend-catalog:
    image: 'chaphe/backend-catalog-image:1.0'
    ports:
      - "8081:8081"
    networks:
      - book-store-network
    environment:
      - MYSQL_DB_HOST=mysql-catalog-store
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_USERNAME=root
      - MYSQL_DB_PASSWORD=password

  # STORE

  backend-store:
    image: 'chaphe/backend-store-image:1.0'
    ports:
      - "8082:8082"
    networks:
      - book-store-network
    environment:
      - MYSQL_DB_HOST=mysql-catalog-store
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_USERNAME=root
      - MYSQL_DB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq


  # Shipping Service
  backend-shipping:
    image: 'chaphe/backend-shipping-image:1.0'
    ports:
      - "3001:3000"  
    networks:
      - book-store-network
    environment:  
      - RABBITMQ_HOST=rabbitmq          

networks:
  book-store-network:
    driver: bridge