apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-backend-deployment
  namespace: library-ns
  labels:
    app: store-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-backend
  template:
    metadata:
      labels:
        app: store-backend
    spec:
      containers:
      - name: store-backend
        image: chaphe/backend-store-image:1.0
        ports:
        - containerPort: 8082
        env:
        - name: MYSQL_DB_HOST
          value: mysql-store-service
        - name: MYSQL_DB_PORT
          value: "3306"
        - name: MYSQL_DB_USERNAME
          value: root
        - name: MYSQL_DB_PASSWORD
          value: password
        - name: RABBITMQ_HOST
          value: rabbitmq #Falta ajustarlo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-frontend-deployment
  namespace: library-ns  
  labels:
    app: store-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-frontend
  template:
    metadata:
      labels:
        app: store-frontend
    spec:
      containers:
      - name: store-frontend
        image: chaphe/frontend-store-image:1.0
        ports:
        - containerPort: 80
        env:
        - name: REVIEWS_URL
          value: http://172.18.7.169:30200
        - name: STORE_URL
          value: http://172.18.7.169:30400 
        - name: CATALOG_URL
          value: http://172.18.7.169:30300 
---
apiVersion: v1
kind: Service
metadata:
  name: store-backend-service
  namespace: library-ns  
spec:
  type: NodePort
  selector:
    app: store-backend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30400
---
apiVersion: v1
kind: Service
metadata:
  name: store-frontend-service
  namespace: library-ns  
spec:
  type: NodePort
  selector:
    app: store-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30401